### ISSUE TITLE
unable to install mean-cli through npm

### ISSUE THREAD

**Issue by shaunstanislaus** [linnovate/mean-cli#106]
shaunstanislaus@Master ~ (master) $ sudo npm install -g mean-cli
Password:
\
> mean-cli@0.10.12 preinstall /usr/local/lib/node_modules/mean-cli
> node ./scripts/preinstall

sh: node: command not found
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "mean-cli"
npm ERR! node v0.12.2
npm ERR! npm  v2.10.0
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! mean-cli@0.10.12 preinstall: `node ./scripts/preinstall`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the mean-cli@0.10.12 preinstall script 'node ./scripts/preinstall'.
npm ERR! This is most likely a problem with the mean-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/preinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls mean-cli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/shaunstanislaus/npm-debug.log
shaunstanislaus@Master ~ (master) $

**Comment by liorkesos** [comment]
Looks like you dont have node installed...
Have you installed the prerequisites?
http://learn.mean.io/#mean-stack-prerequisite-packages
Lior


On Mon, May 25, 2015 at 10:15 AM, Shaun Stanislaus <notifications@github.com
> wrote:

> shaunstanislaus@Master ~ (master) $ sudo npm install -g mean-cli
> Password:
> \
>
> mean-cli@0.10.12 preinstall /usr/local/lib/node_modules/mean-cli
> node ./scripts/preinstall
>
> sh: node: command not found
> npm ERR! Darwin 14.3.0
> npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "mean-cli"
> npm ERR! node v0.12.2
> npm ERR! npm v2.10.0
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
>
> npm ERR! mean-cli@0.10.12 preinstall: node ./scripts/preinstall
> npm ERR! spawn ENOENT
> npm ERR!
> npm ERR! Failed at the mean-cli@0.10.12 preinstall script 'node
> ./scripts/preinstall'.
> npm ERR! This is most likely a problem with the mean-cli package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR! node ./scripts/preinstall
> npm ERR! You can get their info via:
> npm ERR! npm owner ls mean-cli
> npm ERR! There is likely additional logging output above.
>
> npm ERR! Please include the following file with any support request:
> npm ERR! /Users/shaunstanislaus/npm-debug.log
> shaunstanislaus@Master ~ (master) $
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean-cli/issues/106>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by shaunstanislaus** [comment]
i long before already have gulp and bower installed. is still showing the same error.

**Comment by shaunstanislaus** [comment]
Dude, if I didn't installed node I wouldn't be able to execute NPM

**Comment by liorkesos** [comment]
Dude,
Your error explicitly states - *sh: node: command not found*
It was a try..
Lior

On Mon, May 25, 2015 at 1:11 PM, Shaun Stanislaus <notifications@github.com>
wrote:

> Dude, if I didn't installed node I wouldn't be able to execute NPM
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean-cli/issues/106#issuecomment-105197917>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by shaunstanislaus** [comment]
Don't reply to help until you read between the Lines of my errors. Leave it to the node team guys, Btw your company website responsive for mobile didn't work well, check out mind http://www.augmify.com

**Comment by shaunstanislaus** [comment]
i solved it, it is actually the permission issue, i had to chown it with my username.
