### ISSUE TITLE
Add post install for bower install in new packages

### ISSUE THREAD

**Issue by rjVapes** [linnovate/mean-cli#111]
Should we add a block for 
```
  "scripts": {
    "postinstall" : "bower install"
  },
```
It seems a lot of people don't realize they need to add this once adding bower dependencies to cause bower installs to cascade along with npm.

It would add a little time to general npm installs based on how many packages you have, but I doubt it would be much, and if it's a concern someone can always remove the post install scripts for deployment so life is easier on new devs.

**Comment by BrockMcKean** [comment]
Yes. This is related to https://github.com/linnovate/meanio/issues/65 and I think it should be enabled by default. It will have to be to support a complete mean package abstraction.

**Comment by liorkesos** [comment]
This would automatically execute a bower install by default for all packages in your view?

**Comment by rjVapes** [comment]
Yeah, as the npm install cascades through the packages it would cause the bower install to cascade along with it.

**Comment by timelf123** [comment]
Closed by https://github.com/linnovate/mean-cli/commit/6be252554b6f518b8b5837a42b663447ab6a3255
