### ISSUE TITLE
Mean init returns env: node\r: No such file or directory

### ISSUE THREAD

**Issue by mmind-hub** [linnovate/mean-cli#119]
Hi,
Do you know what can i do to solve this ?
I did "su npm install -g mean-cli" successfully
But then i got this "env: node\r: No such file or directory"
I deleted mean-cli and reinstalled node but it stills does not work

**Comment by ilyachenko** [comment]
The same problem.
Today I tried Ubuntu 14.04, 14.10, 15. Any versions of Node 0.10, 4.0 etc always the same problem - No such file or directory.

**Comment by ilyachenko** [comment]
Solved! Was installed old version and now it works: sudo npm install mean-cli@0.10.14 -g

**Comment by rjVapes** [comment]
There was a line ending conflict without a .gitattributes file, so I added one and have updated the registry.  `npm update -g mean-cli` should fix your issues.  Feel free to re-open if not.

**Comment by mmind-hub** [comment]
Thanks a lot ! It works

**Comment by rjVapes** [comment]
The real problem apparently was that I `npm publish`'d from Windows, which uses the files on disk instead of in the repo, so I'll have to remember to publish from OSX from now on.
