### ISSUE TITLE
Command package doesn't create mean.json file inside the new package

### ISSUE THREAD

**Issue by TonyMartinez** [linnovate/mean-cli#130]
$ node -v
v5.10.0
$ npm -v
3.8.3
$ mean -v
0.11.1

Executing this command in a new app:
$ mean package newPackageName

Creates the package but doesn't create mean.json file inside that package.

**Comment by liorkesos** [comment]
It is not supposed to create a mean.json file.
A mean.json file is introduced only if you want the new package to require
a different mean package.
Lior

On Sat, Apr 30, 2016 at 9:13 PM, TonyMartinez <notifications@github.com>
wrote:

> $ node -v
> v5.10.0
> $ npm -v
> 3.8.3
> $ mean -v
> 0.11.1
>
> Executing this command in a new app:
> $ mean package newPackageName
>
> Creates the package but doesn't create mean.json file inside that package.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean-cli/issues/130>
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by TonyMartinez** [comment]
Yes, you are right. But since I upgraded to the last meanio version, without that file the app crash badly:

> "Error: [$injector:nomod] Module 'mean.newPackageName' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument."

I assumed the new code identifies the packages to inject them by the mean.json file.

Thanks for the reply. I'm still looking how all the new code works so I know I'll be wrong on that for sure  :+1:
