### ISSUE TITLE
userWizard bug.

### ISSUE THREAD

**Issue by vpArth** [linnovate/mean-cli#135]
One does not simply pass correct email here:
```
			 var cb = this.async(),
			 re = /^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i,
			 val = re.test(input);
			 if (val) return cb(true);
			 cb('Invalid input for email');
```
We get error here anyway, text message or boolean true.
May be need to call `cb(null, true)` here?

**Comment by timelf123** [comment]
PR welcome

**Comment by vpArth** [comment]
#136 was accidentally open, close this one too, please :)
