### ISSUE TITLE
Fix packages installed with mean init prompt.

### ISSUE THREAD

**Issue by BrockMcKean** [linnovate/mean-cli#92]
This needs to be inspected more closely. mean-admin seems to install and work fine, but other packages (tokens and upload) fail with bower related errors. This is probably due to their package related json files. It may also be due to a fundamental difference in how install and postinstall work, since the same packages install (also producing vague bower related warnings) and work when installed from mean install.

**Comment by liorkesos** [comment]
We removed the installation from the mean init prompt alltogether...
