### ISSUE TITLE
mean-cli install fail :(

### ISSUE THREAD

**Issue by phanthinh** [linnovate/mean-cli#98]
Hi @zohar  @zlokomatic   @bjornkri   @OriPekelman  @AlmogBaku  @brownman 

Can you help me!!

npm WARN engine mean-cli@0.9.20: wanted: {"node":"0.10.x","npm":"2.1.x"} (current: {"node":"0.10.33","npm":"2.6.0"})

> mean-cli@0.9.20 preinstall /root/.nvm/v0.10.33/lib/node_modules/mean-cli
> node ./scripts/preinstall

sh: node: command not found
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "node" "/root/.nvm/v0.10.33/bin/npm" "install" "-g" "mean-cli"
npm ERR! node v0.10.33
npm ERR! npm  v2.6.0
npm ERR! code ELIFECYCLE

npm ERR! mean-cli@0.9.20 preinstall: `node ./scripts/preinstall`
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the mean-cli@0.9.20 preinstall script 'node ./scripts/preinstall'.
npm ERR! This is most likely a problem with the mean-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/preinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls mean-cli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /share/project/npm-debug.log

**Comment by liorkesos** [comment]
You don't have node (which is part of the prerequisites) installed.
